<?php
/**
 * Plugin Name: buyCRED Inline Gateway Switcher
 * Plugin URI:  https://digitallydisruptive.co.uk/
 * Description: Deploys a MutationObserver to inject a dynamic gateway reset mechanism into the myCred inline AJAX checkout form.
 * Version:     1.0.0
 * Author:      Digitally Disruptive - Donald Raymundo
 * Author URI:  https://digitallydisruptive.co.uk/
 * Text Domain: dd-inline-switcher
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly to prevent unauthorized execution.
}

/**
 * Class DD_BuyCred_Inline_Switcher
 * * Handles the logic for observing buyCRED AJAX DOM mutations and injecting
 * a UI mechanism to reset the gateway selection state.
 */
class DD_BuyCred_Inline_Switcher {

	/**
	 * Constructor function.
	 * * Initializes necessary WordPress hooks. We hook into wp_footer to ensure
	 * our vanilla JavaScript is loaded after the DOM and myCred's wrapper exist.
	 */
	public function __construct() {
		add_action( 'wp_footer', array( $this, 'inject_observer_script' ), 99 );
	}

	/**
	 * Injects the JavaScript MutationObserver logic into the footer.
	 * * This script isolates the myCred wrapper and listens for DOM node insertions.
	 * When the gateway checkout UI is detected, it prepends a reset action button.
	 * * @return void
	 */
	public function inject_observer_script() {
		// Verify if we are on a page containing the specific shortcode to prevent unnecessary JS execution.
		global $post;
		if ( ! is_a( $post, 'WP_Post' ) || ! has_shortcode( $post->post_content, 'mycred_buy_form' ) ) {
			return;
		}
		?>
		<script type="text/javascript">
			document.addEventListener('DOMContentLoaded', function() {
				
				// Identify the wrapper myCred uses for its AJAX DOM replacement.
				// We target common classes/IDs generated by the [mycred_buy_form] shortcode.
				const targetNode = document.querySelector('.mycred-buy-form-wrapper, .mycred-buy-form');
				if ( ! targetNode ) return;

				// Configure the observer to watch for direct child modifications.
				const config = { childList: true, subtree: true };

				// Callback function to execute when mutations are observed.
				const callback = function( mutationsList, observer ) {
					for ( let mutation of mutationsList ) {
						if ( mutation.type === 'childList' ) {
							
							// Check if the inline checkout form has successfully rendered in the DOM.
							const isCheckoutActive = targetNode.querySelector('.mycred-buycred-gateway-form, form[action*="gateway"]');
							const switcherExists   = targetNode.querySelector('.dd-gateway-reset-btn');

							// If the checkout is active and our button hasn't been injected yet.
							if ( isCheckoutActive && ! switcherExists ) {
								
								// Construct the reset UI element.
								const resetBtn = document.createElement('a');
								resetBtn.href = "javascript:void(0);";
								resetBtn.className = "dd-gateway-reset-btn";
								resetBtn.innerHTML = "&larr; Change Payment Method";
								
								// Apply inline styling (can be moved to external CSS if preferred).
								resetBtn.style.cssText = "display: inline-block; margin-bottom: 20px; font-weight: 600; color: #d9534f; text-decoration: none; cursor: pointer; transition: opacity 0.2s ease;";
								resetBtn.onmouseover = function() { this.style.opacity = '0.7'; };
								resetBtn.onmouseout = function() { this.style.opacity = '1'; };
								
								// Action: Force a page reload to clear the temporary AJAX transaction state
								// and return the user to the initial gateway selection UI.
								resetBtn.onclick = function() {
									window.location.reload();
								};

								// Inject the button directly above the gateway payment form.
								isCheckoutActive.parentNode.insertBefore(resetBtn, isCheckoutActive);
							}
						}
					}
				};

				// Instantiate and execute the observer.
				const observer = new MutationObserver( callback );
				observer.observe( targetNode, config );
			});
		</script>
		<?php
	}
}

// Instantiate the architecture.
new DD_BuyCred_Inline_Switcher();