<?php
if (! defined('ABSPATH')) {
    exit; // Exit if accessed directly to prevent direct file execution.
}
/**
 * Plugin Name: PMPro Checkout Button - Force Update
 * Description: Uses MutationObserver to forcefully rename the checkout button on the membership checkout page, overriding payment gateways.
 * Author: Digitally Disruptive - Donald Raymundo
 * Author URI: https://digitallydisruptive.co.uk/
 * Version: 1.1.0
 */

if (! defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

function dd_pmpro_force_checkout_text_observer()
{
    // 1. Target the specific checkout page URL provided
    // We check if we are on the 'membership-checkout' page.
    if (! is_page(1551)) {
        return;
    }
?>
    <script type="text/javascript">
        jQuery(document).ready(function($) {

            // CONFIGURATION: Set your desired button text here
            const newText = "Submit";
            const targetButtonId = "pmpro_btn-submit";

            const $btn = $('#' + targetButtonId);

            if ($btn.length === 0) return;

            // Function to apply the text change
            const forceText = () => {
                if ($btn.is('input')) {
                    // For <input type="submit">
                    if ($btn.val() !== newText) {
                        $btn.val(newText);
                    }
                } else {
                    // For <button> elements
                    if ($btn.text() !== newText) {
                        $btn.text(newText);
                    }
                }
            };

            // 1. Apply immediately
            forceText();

            // 2. Set up a MutationObserver to watch for changes
            // This detects if Stripe/PayPal/Theme tries to overwrite our text
            const observer = new MutationObserver(function(mutations) {
                mutations.forEach(function(mutation) {
                    forceText();
                });
            });

            // Start observing the button for attribute changes (like 'value' or 'disabled') or child list changes (text inside <button>)
            observer.observe($btn[0], {
                attributes: true,
                childList: true,
                subtree: true
            });
        });
    </script>
<?php
}
add_action('wp_footer', 'dd_pmpro_force_checkout_text_observer', 99);



/**
 * Intercepts and modifies localization strings for Paid Memberships Pro.
 * * This function hooks into the WordPress 'gettext' translation system. It checks 
 * if the text domain is PMPro and if the original string matches known lost 
 * password variants, returning a custom string if a match is found.
 *
 * @param string $translated_text The translated text generated by WordPress.
 * @param string $text            The original unmodified string.
 * @param string $domain          The text domain associated with the string.
 * @return string                 The newly defined text or the original translated text.
 */
function dd_pmpro_custom_lost_password_text($translated_text, $text, $domain)
{
    // Strictly target the PMPro text domain to prevent global overrides.
    if ('paid-memberships-pro' === $domain) {

        // Match common PMPro lost password strings. 
        // Note: Exact string matching is required for gettext to work.
        if ('Forgot Password?' === $text || 'Lost Password?' === $text || 'Lost your password?' === $text) {

            // Define the new custom text here.
            $translated_text = esc_html__('Reset password', 'paid-memberships-pro');
        }
    }

    return $translated_text;
}
add_filter('gettext', 'dd_pmpro_custom_lost_password_text', 20, 3);

/**
 * Appends the current user's membership level slug to the body class array.
 * * This function hooks into 'body_class' to inject custom CSS classes based on 
 * the current user's authentication status and membership tier. It checks for 
 * Paid Memberships Pro, WooCommerce Memberships, and falls back to standard 
 * WP roles to ensure a CSS-friendly slug is always generated.
 *
 * @param array $classes An array of existing body classes generated by WordPress.
 * @return array The filtered array of body classes with membership slugs appended.
 */
function dd_append_membership_level_body_class($classes)
{

    // Handle unauthenticated users immediately to reduce processing overhead
    if (! is_user_logged_in()) {
        $classes[] = 'membership-guest';
        return $classes;
    }

    $user_id = get_current_user_id();
    $membership_slugs = array();

    // 1. Paid Memberships Pro (PMPro) Integration
    if (function_exists('pmpro_getMembershipLevelForUser')) {
        $level = pmpro_getMembershipLevelForUser($user_id);
        if (! empty($level) && isset($level->name)) {
            // Converts the string (e.g., "Gold Tier") to a slug (e.g., "pmpro-level-gold-tier")
            $membership_slugs[] = 'pmpro-level-' . sanitize_title($level->name);
            $membership_slugs[] = 'pmpro-level-' . sanitize_title($level->id);
        }
    }


    // 2. Fallback: Standard WordPress User Role
    // If no membership plugin data is found, utilize the assigned WP roles
    if (empty($membership_slugs)) {
        $user = get_userdata($user_id);
        if (! empty($user->roles) && is_array($user->roles)) {
            foreach ($user->roles as $role) {
                $membership_slugs[] = 'role-' . sanitize_title($role);
            }
        }
    }

    // Merge new classes with existing ones, ensuring no duplicates are added
    if (! empty($membership_slugs)) {
        $classes = array_merge($classes, array_unique($membership_slugs));
    }

    return $classes;
}
add_filter('body_class', 'dd_append_membership_level_body_class');



/**
 * Overrides the default logout redirect destination with the PMPro login page URL.
 * Includes a validation check to ensure PMPro is active before attempting to retrieve its routing.
 *
 * @param string  $redirect_to           The default redirect destination URL.
 * @param string  $requested_redirect_to The requested redirect destination URL passed as a parameter.
 * @param WP_User $user                  The WP_User object for the user that is logging out.
 * @return string                        The customized PMPro login URL or the fallback default URL.
 */
function dd_custom_pmpro_logout_redirect($redirect_to, $requested_redirect_to, $user)
{

    // Validate PMPro core functionality exists to prevent fatal errors if the plugin is deactivated
    if (function_exists('pmpro_url')) {

        // Retrieve the designated PMPro login page URL via the core API
        $pmpro_login_url = pmpro_url('login');

        // Ensure a valid URL was returned before applying the redirect override
        if (! empty($pmpro_login_url)) {
            return $pmpro_login_url;
        }
    }

    // Fall back to default WordPress routing if PMPro is unavailable or the URL is empty
    return $redirect_to;
}

// Hook into the logout_redirect filter with a standard priority of 10, accepting 3 arguments
add_filter('logout_redirect', 'dd_custom_pmpro_logout_redirect', 10, 3);

/**
 * Adjusts the profile_start_date and initial_payment for the new membership level during checkout.
 * This ensures the new billing cycle appends to the existing subscription's next payment date appropriately.
 *
 * @param object $level The membership level object being processed at checkout.
 * @return object The modified membership level object.
 */
function dd_pmpro_append_billing_cycle_on_switch($level)
{
    // Ensure the user is authenticated and the level has recurring billing configured.
    if (! is_user_logged_in() || empty($level) || empty($level->billing_amount)) {
        return $level;
    }

    $user_id = get_current_user_id();
    $old_level = pmpro_getMembershipLevelForUser($user_id);

    // Abort if the user lacks an active subscription or is attempting to checkout for the exact same level.
    if (empty($old_level) || $old_level->id == $level->id) {
        return $level;
    }

    // Retrieve the UNIX timestamp for the next scheduled payment of the current active subscription.
    $next_payment_timestamp = pmpro_next_payment($user_id);

    // If no future payment date exists (e.g., cancelled or expired), rely on default PMPro behavior.
    if (! $next_payment_timestamp || $next_payment_timestamp <= current_time('timestamp')) {
        return $level;
    }

    // Extract cycle parameters for comparison and calculation.
    $new_cycle_number = ! empty($level->cycle_number) ? (int) $level->cycle_number : 1;
    $new_cycle_period = ! empty($level->cycle_period) ? $level->cycle_period : 'Month';

    $old_cycle_period = ! empty($old_level->cycle_period) ? $old_level->cycle_period : 'Month';

    // Determine if this is a shift from Annual to Monthly (Downgrade) or Monthly to Annual (Upgrade).
    if ($old_cycle_period === 'Year' && $new_cycle_period === 'Month') {
        // DOWNGRADE SCENARIO: Annual to Monthly
        // User shouldn't pay today since they already paid for the year. 
        // The new monthly billing should commence exactly when the current annual cycle ends.
        $level->initial_payment = 0;
        $level->profile_start_date = date("Y-m-d\TH:i:s", $next_payment_timestamp);
    } else {
        // UPGRADE SCENARIO: Monthly to Annual 
        // User pays the initial fee today (covering the new annual cycle). 
        // The next recurring payment pushes out exactly one year from their CURRENT next payment date.
        // E.g., Upgrading on Mar 12. Current next payment: Apr 12 2024. New Start: Apr 12 2025.
        $strtotime_modifier = '+' . $new_cycle_number . ' ' . $new_cycle_period;
        $new_start_timestamp = strtotime($strtotime_modifier, $next_payment_timestamp);

        // Format the date for PMPro gateways (requires Y-m-d\TH:i:s format).
        $level->profile_start_date = date("Y-m-d\TH:i:s", $new_start_timestamp);
    }

    return $level;
}
add_filter('pmpro_checkout_level', 'dd_pmpro_append_billing_cycle_on_switch', 10, 1);



/**
 * Intercepts frontend page loads to handle two specific free-tier redirections:
 * 1. Redirects users completing checkout for the Free Level (15) directly to the pricing page.
 * 2. Forcefully redirects Free members to the pricing page if they access the dashboard template,
 *    while explicitly exempting core PMPro functional pages to prevent lockouts.
 *
 * @return void
 */
function dd_force_free_members_to_upgrade()
{
    // 1. Abort if Paid Memberships Pro is not active
    if (! function_exists('pmpro_hasMembershipLevel')) {
        return;
    }

    // 2. Abort for backend, AJAX, or logged-out users
    if (! is_user_logged_in() || is_admin() || wp_doing_ajax() || wp_is_json_request()) {
        return;
    }

    global $post, $pmpro_pages;

    // 3. NEW LOGIC: Intercept Free Level (15) Confirmation Page
    // We do this BEFORE the exemption check so it catches the free tier immediately.
    if (! empty($pmpro_pages['confirmation']) && is_page($pmpro_pages['confirmation'])) {
        $level_id = isset($_GET['pmpro_level']) ? intval($_GET['pmpro_level']) : 0;

        if ($level_id === 15) {
            $redirect_url = pmpro_url('levels');
            if ($redirect_url) {
                wp_safe_redirect($redirect_url);
                exit;
            }
        }
    }

    // 4. DEFENSE IN DEPTH: Explicitly exempt core PMPro functional pages
    if (! empty($pmpro_pages)) {
        // Includes 'account' and 'profile' to the exempt keys
        $exempt_keys = array('levels', 'checkout', 'billing', 'cancel', 'confirmation', 'account', 'profile');
        $exempt_page_ids = array();

        foreach ($exempt_keys as $key) {
            if (! empty($pmpro_pages[$key])) {
                $exempt_page_ids[] = $pmpro_pages[$key];
            }
        }

        // Exemption A: Is this an exact match for a core PMPro page?
        if (is_page($exempt_page_ids)) {
            return;
        }

        // Exemption B: Is this a child page of the Membership Account page? (e.g., /membership-account/your-profile/)
        if (! empty($pmpro_pages['account']) && isset($post->post_parent) && $post->post_parent == $pmpro_pages['account']) {
            return;
        }
    }

    // 5. Abort if the current page is NOT using the Dashboard template
    if (! is_page_template('templates/page-dashboard.php')) {
        return;
    }

    // 6. Define the exact ID of your Free Membership Level
    $free_level_ids = array(15);

    // 7. Evaluate if the current user possesses the free level
    if (pmpro_hasMembershipLevel($free_level_ids)) {

        // Retrieve the dynamic URL for the PMPro Levels/Pricing page
        $redirect_url = pmpro_url('levels');

        // Execute the redirect
        if ($redirect_url) {
            wp_safe_redirect($redirect_url);
            exit;
        }
    }
}
add_action('template_redirect', 'dd_force_free_members_to_upgrade');


/**
 * Transforms the PMPro Checkout into a cleaner, influencer-style layout.
 * Reorders DOM elements, securely hides the payment plan selector, builds an influencer-style 
 * Summary block ABOVE the payment info, injects the user avatar, and populates uniform bullet points.
 *
 * @return void
 */
function dd_influencer_style_pmpro_checkout()
{
    global $pmpro_pages;

    // Abort if we are not on the explicit PMPro checkout page
    if (empty($pmpro_pages['checkout']) || ! is_page($pmpro_pages['checkout'])) {
        return;
    }

    // 1. EXTRACT REAL PLAN NAME & DESCRIPTION FROM PMPRO DATABASE
    $level_id = isset($_REQUEST['level']) ? intval($_REQUEST['level']) : 0;
    $real_plan_name = 'Membership Plan'; // Fallback
    $plan_description = '';

    if ($level_id > 0 && function_exists('pmpro_getLevel')) {
        $level = pmpro_getLevel($level_id);
        if (! empty($level)) {
            $real_plan_name = $level->name;
            if (! empty($level->description)) {
                // Strip tags so the description fits cleanly inside a single bullet point
                $plan_description = wp_strip_all_tags($level->description);
            }
        }
    }

    // Safely get the dynamic Membership Levels page URL for the "Change plan" link
    $levels_url = function_exists('pmpro_url') ? pmpro_url('levels') : '/membership-levels/';

    // 2. DEFINE YOUR GLOBAL PLAN DETAILS HERE
    // By only using 'default', these bullets will apply to ALL payment plans uniformly.
    $dynamic_plan_details = [
        'default' => [
            'account_type' => '1 Account',
            'bullets' => [
                'Enjoy unlimited access to your selected plan features.',
                'From the starting date shown, you\'ll be charged for your updated subscription.',
                'Cancel anytime online. <a href="/terms-of-use/">Terms apply</a>.'
            ]
        ]
    ];

    // Execute your custom avatar shortcode safely
    $avatar_html = do_shortcode('[user_avatar]');
?>
    <style>
        /* influencer-style CSS Overrides for PMPro */


        #pmpro_form {
            max-width: 600px;
            margin: 0 auto;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #000;
        }

        .dd-influencer-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding-bottom: 15px;
        }


        .dd-checkout-title-row {
            display: flex;
            justify-content: space-between;
            align-items: baseline;
            margin-bottom: 20px;
            border-bottom: 1px solid #e5e5e5;
            padding-bottom: 20px;
        }

        .dd-checkout-title-row h2 {
            font-size: clamp(20px, 1.5vw, 32px) !important;
            font-weight: 700 !important;
            margin: 0 !important;
            color: #000;
            letter-spacing: -0.5px;
        }

        .dd-checkout-title-row a {
            color: var(--e-global-color-accent);
            text-decoration: underline;
            font-weight: 500;
            font-size: 14px;
            transition: color 0.2s ease;
        }

        .dd-checkout-title-row a:hover {
            color: #000;
        }

        .dd-avatar-wrapper {
            width: 60px;
            height: 60px;
            border-radius: 50%;
            overflow: hidden;
            background: #eee;
            border: 2px solid #ddd;
        }

        .dd-avatar-wrapper img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        /* Neutralize the heavy boxed styling of PMPro default sections */
        .pmpro_checkout-section {
            background: transparent !important;
            border: none !important;
            box-shadow: none !important;
            padding: 0 !important;
            margin-bottom: 30px !important;
        }

        .pmpro_checkout-section h3,
        .pmpro_checkout-section h2 {
            font-size: 20px !important;
            font-weight: 700 !important;
            border: none !important;
            margin-bottom: 15px !important;
            padding-bottom: 0 !important;
            color: #000;
        }

        /* Hide unwanted default sections and specific PMPro fields */
        #pmpro_level_cost,
        #pmpropp_payment_plans,
        #pmpro_pricing_fields,
        #pmpro_user_fields,
        #pmpropp_select_payment_plan {
            display: none !important;
        }



        .pmpro_form_field-radio-items.pmpro_form_field-radio-items.pmpro_form_field-radio-items {
            flex-direction: column;
            gap: 0;
        }

        .pmpro_form_field-radio-item.pmpro_form_field-radio-item.pmpro_form_field-radio-item {
            width: 100%;
        }

        .pmpro_form_field-radio-item.pmpro_form_field-radio-item.pmpro_form_field-radio-item .pmpro_form_label {
            font-size: 1rem;
            color: #000;
        }

        .pmpro_form_field-radio-item.pmpro_form_field-radio-item.pmpro_form_field-radio-item input {
            width: auto;
        }

        .pmpro_check_instructions.pmpro_check_instructions {
            box-shadow: none;
            border: none;
            border-radius: 0;
            margin-top: 0;
        }

        .pmpro_check_instructions.pmpro_check_instructions .pmpro_card_title {
            padding: 0;
        }

        .pmpro_check_instructions.pmpro_check_instructions .pmpro_card_content {
            padding: 0;
        }

        #pmpro_payment_information_fields .pmpro_card,
        #pmpro_payment_method .pmpro_card {
            border-radius: 0;
            margin: 0;
            border: none;
            box-shadow: none;
        }

        #pmpro_payment_method .pmpro_card {
            margin-bottom: 30px;
        }

        #pmpro_payment_information_fields .pmpro_card .pmpro_card_content,
        #pmpro_payment_method .pmpro_card .pmpro_card_content {
            padding: 0;
        }

        /* influencer Card Styles */
        #dd-influencer-summary {
            margin-top: 20px !important;
            margin-bottom: 20px !important;
            border-bottom: 1px solid #e5e5e5 !important;
            padding-bottom: 20px !important;
        }

        .infl-summary-card {
            background: transparent;
        }

        .infl-header-row {
            display: flex;
            align-items: center;
            margin-bottom: 25px;
        }

        .infl-icon {
            width: 50px;
            height: 50px;
            background: var(--e-global-color-secondary);
            border-radius: 6px;
            display: flex;
            align-items: center;
            justify-content: flex-end;
            margin-right: 15px;
            color: #fff;
        }

        .infl-icon img {
            width: 30px;
            height: 30px;
        }

        .infl-plan-info {
            flex-grow: 1;
        }

        .infl-plan-info h4 {
            margin: 0 0 2px 0 !important;
            font-size: 16px !important;
            font-weight: 700 !important;
        }

        .infl-plan-info span {
            font-size: 14px;
            color: #b3b3b3;
        }

        .infl-price-info {
            text-align: right;
        }

        .infl-price-info h4 {
            margin: 0 0 2px 0 !important;
            font-size: 16px !important;
            font-weight: 700 !important;
        }

        .infl-price-info span {
            font-size: 14px;
            color: #b3b3b3;
        }

        body:not(.page-id-4144) span#pmpro_submit_span {
            width: 100%;
        }


        .pmpro_form_submit {
            flex-direction: column;
        }

        /* Timeline Styles */
        .infl-timeline {
            position: relative;
            padding-left: 15px;
            margin-bottom: 20px;
        }

        .infl-timeline::before {
            content: '';
            position: absolute;
            left: 19px;
            top: 10px;
            bottom: 25px;
            width: 1px;
            background: #000;
        }

        .infl-timeline-item {
            position: relative;
            padding-left: 20px;
            margin-bottom: 20px;
        }

        .infl-dot {
            position: absolute;
            left: 0;
            top: 6px;
            width: 9px;
            height: 9px;
            border-radius: 50%;
            background: #000;
            z-index: 2;
        }

        .infl-dot.hollow {
            background: #fff;
            border: 2px solid #000;
            left: 0px;
            width: 9px;
            height: 9px;
        }

        .infl-content p {
            margin: 0 0 2px 0 !important;
            font-size: 15px;
            font-weight: 500;
        }

        .infl-content span {
            font-size: 14px;
            color: #b3b3b3;
        }

        /* Bullet Points */
        .infl-bullets.infl-bullets {
            list-style: none;
            padding: 0;
            margin: 0;
            font-size: 13px !important;
            color: #6a6a6a;
            line-height: 1.5;
        }

        .infl-bullets li {
            position: relative;
            padding-left: 15px;
            margin-bottom: 6px;
        }

        .infl-bullets li::before {
            content: '•';
            position: absolute;
            left: 0;
            top: 0;
            color: #6a6a6a;
        }

        .infl-bullets a {
            color: #6a6a6a;
            text-decoration: underline;
        }

        /* Submit Button */
        #pmpro_btn-submit {
            background-color: #1ed760 !important;
            color: #000 !important;
            border-radius: 500px !important;
            padding: 16px 30px !important;
            font-size: 16px !important;
            font-weight: 700 !important;
            border: none !important;
            width: 100% !important;
            text-transform: none !important;
            transition: transform 0.2s ease, background-color 0.2s ease;
            margin-top: 20px;
        }

        #pmpro_btn-submit:hover {
            background-color: #1fdf64 !important;
            transform: scale(1.02);
        }

        /* Clean up residual Account Info if logged out */
        .dd-clean-account-info h2,
        .dd-clean-account-info h3,
        .dd-clean-account-info hr,
        .dd-clean-account-info p.pmpro_logged_in_text {
            display: none !important;
        }
    </style>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            if (typeof jQuery === 'undefined') return;
            var $ = jQuery;

            var avatarHtml = <?php echo wp_json_encode($avatar_html); ?>;
            var dynamicPlanMeta = <?php echo wp_json_encode($dynamic_plan_details); ?>;
            var realPlanName = <?php echo wp_json_encode($real_plan_name); ?>;
            var planDescription = <?php echo wp_json_encode($plan_description); ?>;
            var levelsUrl = <?php echo wp_json_encode($levels_url); ?>;

            // 1. Inject Header and Title Row immediately
            var headerHtml = '<div class="dd-influencer-header">' +
                '<div class="dd-influencer-logo"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="134.712" height="68.251" viewBox="0 0 134.712 68.251"><defs><clipPath id="clip-path"><rect id="Rectangle_9" data-name="Rectangle 9" width="134.712" height="68.251" fill="currentColor"/></clipPath></defs><g id="Group_9" data-name="Group 9" transform="translate(0 0)"><g id="Group_8" data-name="Group 8" transform="translate(0 0)" clip-path="url(#clip-path)"><path id="Path_6" data-name="Path 6" d="M7.342,45.71H6.154V54.9H2.659V33.234H7.2c4.893,0,8.108,2.306,8.108,6.116a5.3,5.3,0,0,1-3.7,5.067c2.866,1.083,4.753,7.758,8.807,7.758l-.7,2.936c-6.92,0-7.164-9.4-12.372-9.4m.21-9.75h-1.4v7.059h1.5c2.481,0,4.194-1.294,4.194-3.6,0-2.2-1.782-3.459-4.3-3.459" transform="translate(-1.191 -14.885)" fill="currentColor"/><path id="Path_7" data-name="Path 7" d="M76.659,54.929H71.522V33.3h4.264c5,0,8.387,1.572,8.387,5.452A3.966,3.966,0,0,1,81.1,42.8c3.075.489,4.962,2.271,4.962,5.731,0,4.683-3.6,6.4-9.4,6.4M76.17,35.988H75.017v5.7h1.4c3.285,0,4.229-1.083,4.229-2.761.035-2.062-1.328-2.936-4.473-2.936m1.4,8.422H75.017v7.653h2.551c3.984,0,4.823-1.573,4.928-3.7,0-1.887-.874-3.949-4.928-3.949" transform="translate(-32.034 -14.914)" fill="currentColor"/><path id="Path_8" data-name="Path 8" d="M118.811,54.929h-5.137V33.3h4.264c5,0,8.387,1.572,8.387,5.452A3.966,3.966,0,0,1,123.25,42.8c3.075.489,4.963,2.271,4.963,5.731,0,4.683-3.6,6.4-9.4,6.4m-.489-18.941h-1.153v5.7h1.4c3.285,0,4.229-1.083,4.229-2.761.035-2.062-1.328-2.936-4.473-2.936m1.4,8.422h-2.551v7.653h2.551c3.984,0,4.823-1.573,4.928-3.7,0-1.887-.874-3.949-4.928-3.949" transform="translate(-50.914 -14.914)" fill="currentColor"/><path id="Path_9" data-name="Path 9" d="M165.111,54.926c-6.221,0-11.182-4.055-11.182-11.149,0-7.059,4.961-11.113,11.182-11.113S176.3,36.718,176.3,43.812c0,7.059-4.963,11.114-11.184,11.114m0-19.361c-4.158,0-7.583,3.04-7.583,8.213,0,5.278,3.425,8.213,7.583,8.213s7.584-2.936,7.584-8.178c0-5.207-3.425-8.247-7.584-8.247" transform="translate(-68.944 -14.63)" fill="currentColor"/><path id="Path_10" data-name="Path 10" d="M213.754,39.84V54.448h-3.5V32.222h.489l14.643,15.132V32.781h3.494V54.9H228.4Z" transform="translate(-94.174 -14.432)" fill="currentColor"/><path id="Path_11" data-name="Path 11" d="M7.8,105.564H2.659V83.932H6.923c5,0,8.387,1.572,8.387,5.452a3.966,3.966,0,0,1-3.075,4.054c3.075.489,4.962,2.271,4.962,5.731,0,4.683-3.6,6.4-9.4,6.4M7.307,86.623H6.154v5.7h1.4c3.285,0,4.229-1.083,4.229-2.761.035-2.062-1.328-2.936-4.473-2.936m1.4,8.422H6.154V102.7H8.705c3.984,0,4.823-1.573,4.928-3.7,0-1.887-.874-3.949-4.928-3.949" transform="translate(-1.191 -37.593)" fill="currentColor"/><path id="Path_12" data-name="Path 12" d="M54.1,105.56c-6.221,0-11.183-4.054-11.183-11.148,0-7.059,4.962-11.113,11.183-11.113s11.183,4.054,11.183,11.148c0,7.059-4.962,11.113-11.183,11.113m0-19.361c-4.158,0-7.583,3.04-7.583,8.213,0,5.278,3.425,8.213,7.583,8.213s7.583-2.936,7.583-8.178c0-5.207-3.424-8.247-7.583-8.247" transform="translate(-19.22 -37.309)" fill="currentColor"/><path id="Path_13" data-name="Path 13" d="M97.3,105.536H93.421l7.933-12.686-5.7-8.982h4.019l3.53,6.326,3.53-6.326h4.019l-5.661,8.982,7.9,12.686h-3.88l-5.905-10.169Z" transform="translate(-41.843 -37.564)" fill="currentColor"/><path id="Path_14" data-name="Path 14" d="M141.863,120.176a2.048,2.048,0,0,1-2.237-2.062,2,2,0,0,1,2.237-2.027,2.051,2.051,0,0,1,2.306,2.062,2.082,2.082,0,0,1-2.306,2.027" transform="translate(-62.538 -51.995)" fill="currentColor"/><path id="Path_15" data-name="Path 15" d="M4.717,1.362,2.708,10.83H.978L2.97,1.362H0L.612,0h7.2L7.529,1.362Z" transform="translate(0 0)" fill="currentColor"/><path id="Path_16" data-name="Path 16" d="M24.528,10.83l1.118-5.275h-5.66L18.868,10.83H17.121L19.41,0h1.747l-.891,4.192h5.66L26.816,0h1.765L26.275,10.83Z" transform="translate(-7.669 0)" fill="currentColor"/><path id="Path_17" data-name="Path 17" d="M46.163,1.362l-.611,2.9h3.371l-.279,1.362H45.255l-.8,3.826H50.3l-.612,1.38H42.408L44.7,0h6.166l-.3,1.362Z" transform="translate(-18.994 0)" fill="currentColor"/><path id="Path_18" data-name="Path 18" d="M47.471,37.22V54.977h3.495V33.4Z" transform="translate(-21.262 -14.961)" fill="currentColor"/></g></g></svg></div>' +
                '<div class="dd-avatar-wrapper">' + (avatarHtml ? avatarHtml : '') + '</div>' +
                '</div>' +
                '<div class="dd-checkout-title-row">' +
                '<h2>Checkout</h2>' +
                '<a href="' + levelsUrl + '">Change plan</a>' +
                '</div>';
            $('#pmpro_form').prepend(headerHtml);

            // Wait for the Payment Plans DOM to be fully injected via AJAX
            var pollDOM = setInterval(function() {
                var $radios = $('input[name="pmpropp_chosen_plan"]');
                var $levelCost = $('#pmpro_level_cost');

                // Only proceed if PMPro has successfully rendered the pricing elements
                if ($radios.length > 0 || $levelCost.length > 0) {
                    clearInterval(pollDOM);

                    // 2. Safely parse URL to enforce accurate plan selection
                    var urlParams = new URLSearchParams(window.location.search);
                    var currentLevelId = urlParams.get('level') || '';
                    var chosenPlanUrlValue = urlParams.get('pmpropp_chosen_plan');
                    var planDetails = dynamicPlanMeta[currentLevelId] ? dynamicPlanMeta[currentLevelId] : dynamicPlanMeta['default'];

                    // Force PMPro to check the correct radio button based on the URL (prevents Annual defaulting bugs)
                    if ($radios.length > 0) {
                        if (chosenPlanUrlValue) {
                            $radios.filter('[value="' + chosenPlanUrlValue + '"]').prop('checked', true);
                        } else if (currentLevelId) {
                            $radios.filter('[value="' + currentLevelId + '"]').prop('checked', true);
                        }
                    }

                    // 3. Hide Native Elements
                    var $paymentPlanWrapper = $('#pmpropp_payment_plans').closest('.pmpro_checkout-section');
                    if ($paymentPlanWrapper.length === 0) $paymentPlanWrapper = $('#pmpropp_payment_plans');
                    $paymentPlanWrapper.hide();
                    $paymentPlanWrapper.prev('h2, h3, hr').hide();

                    $('.pmpro_checkout-section h2, .pmpro_checkout-section h3').each(function() {
                        var txt = $(this).text().trim();
                        if (txt.indexOf('Payment Plan') !== -1 || txt.indexOf('Membership Information') !== -1) {
                            $(this).hide();
                            if ($(this).siblings().length === 0) $(this).closest('.pmpro_checkout-section').hide();
                        }
                    });

                    // 4. Extract Pricing Data explicitly from the checked radio
                    var labelText = $('input[name="pmpropp_chosen_plan"]:checked').siblings('label').text().trim() || $levelCost.text().trim();

                    var planName = realPlanName;
                    var isAnnual = labelText.toLowerCase().includes('annual') || labelText.toLowerCase().includes('year');
                    if (isAnnual) planName = planName + " (Annual)";

                    var nowPrice = "₱0.00";
                    var recurringPrice = "";
                    var cycle = "month";
                    var trialDays = 0;

                    var nowMatch = labelText.match(/(\$[0-9,.]+)\s+now/i);
                    if (nowMatch) nowPrice = nowMatch[1];

                    var recMatch = labelText.match(/(\$[0-9,.]+)\s+per\s+([a-zA-Z]+)/i);
                    if (recMatch) {
                        recurringPrice = recMatch[1];
                        cycle = recMatch[2].toLowerCase();
                    }

                    var trialMatch = labelText.match(/(\d+)\s+day trial/i);
                    if (trialMatch) trialDays = parseInt(trialMatch[1], 10);

                    if (!nowMatch && recMatch) {
                        nowPrice = recurringPrice;
                    }

                    var options = {
                        month: 'short',
                        day: 'numeric',
                        year: 'numeric'
                    };
                    var today = new Date();
                    var startDateStr = "Now";

                    if (trialDays > 0) {
                        var startDate = new Date();
                        startDate.setDate(today.getDate() + trialDays);
                        startDateStr = startDate.toLocaleDateString('en-US', options);
                    }

                    // Build Dynamic Bullets from Array
                    var bulletsHtml = '';

                    // Inject the PMPro database description as the very first bullet
                    if (planDescription) {
                        bulletsHtml += '<li>' + planDescription + '</li>';
                    }

                    planDetails.bullets.forEach(function(bullet) {
                        bulletsHtml += '<li>' + bullet + '</li>';
                    });

                    // 5. Build Summary HTML
                    var influencerHtml = `
                    <div class="infl-summary-card">
                        <div class="infl-header-row">
                            <div class="infl-icon">
                               <img src="/wp-content/uploads/2026/02/cropped-cropped-cropped-favicon-192x192-1.png" alt="Plan Icon">
                            </div>
                            <div class="infl-plan-info">
                                <h4>${planName}</h4>
                                <span>${planDetails.account_type}</span>
                            </div>
                            <div class="infl-price-info">
                                <h4>${recurringPrice} </h4>
                                <span>/${cycle}</span>
                            </div>
                        </div>
                        <div class="infl-timeline">
                            <div class="infl-timeline-item">
                                <div class="infl-dot filled"></div>
                                <div class="infl-content">
                                    <p><strong>Now:</strong> ${nowPrice}</p>
                                    <span>${realPlanName}</span>
                                </div>
                            </div>
                            <div class="infl-timeline-item">
                                <div class="infl-dot hollow"></div>
                                <div class="infl-content">
                                    <p><strong>Starting ${startDateStr}:</strong> ${recurringPrice} /${cycle}</p>
                                    <span>${planName}</span>
                                </div>
                            </div>
                        </div>
                        <ul class="infl-bullets">
                            ${bulletsHtml}
                        </ul>
                    </div>`;

                    // 6. Inject Summary Block
                    var $summarySection = $('<div id="dd-influencer-summary" class="pmpro_checkout-section"></div>');
                    $summarySection.append(influencerHtml);

                    // Map potential insertion anchors
                    var $paymentPlanSelector = $('#pmpropp_select_payment_plan').closest('.pmpro_checkout-section');
                    if (!$paymentPlanSelector.length) $paymentPlanSelector = $('#pmpropp_select_payment_plan');

                    var $paymentMethodSelector = $('#pmpro_payment_method').closest('.pmpro_checkout-section');
                    if (!$paymentMethodSelector.length) $paymentMethodSelector = $('#pmpro_payment_method');

                    var $paymentFields = $('#pmpro_payment_information_fields').closest('.pmpro_checkout-section');
                    if (!$paymentFields.length) $paymentFields = $('#pmpro_payment_information_fields');

                    // Prioritize layout injection hierarchy 
                    if ($paymentPlanSelector.length) {
                        $paymentPlanSelector.before($summarySection);
                    } else if ($paymentMethodSelector.length) {
                        $paymentMethodSelector.before($summarySection);
                    } else if ($paymentFields.length) {
                        $paymentFields.before($summarySection);
                    } else {
                        $('#pmpro_form').prepend($summarySection);
                    }

                    // 7. Clean Up Account Information
                    var $accInfo = $('#pmpro_account').closest('.pmpro_checkout-section');
                    if (!$accInfo.length) $accInfo = $('#pmpro_account');
                    if (!$accInfo.length) $accInfo = $('.pmpro_checkout-section:contains("Account Information")');

                    if ($accInfo.length) {
                        $accInfo.addClass('dd-clean-account-info');
                        if ($accInfo.find('input[type="text"]').length > 0 || $accInfo.find('input[type="password"]').length > 0) {
                            $summarySection.append($accInfo);
                            $accInfo.show();
                        } else {
                            $accInfo.hide();
                        }
                    }

                    if ($levelCost.length) $levelCost.hide();
                }
            }, 100); // Poll every 100ms until DOM is ready
        });
    </script>
<?php
}
add_action('wp_footer', 'dd_influencer_style_pmpro_checkout', 50);

/**
 * Renders the First Name and Last Name input fields on the PMPro checkout form.
 * Hooks into 'pmpro_checkout_after_password' to insert the fields directly 
 * within the user account credential section. Automatically pre-populates 
 * data for authenticated users to prevent data entry redundancy.
 *
 * @return void
 */
function dd_pmpro_add_name_fields_to_checkout()
{
    $current_user_id = get_current_user_id();

    // Prioritize active POST request data for repopulation, fallback to existing user meta if authenticated.
    $first_name = isset($_REQUEST['first_name']) ? sanitize_text_field(wp_unslash($_REQUEST['first_name'])) : ($current_user_id ? get_user_meta($current_user_id, 'first_name', true) : '');
    $last_name  = isset($_REQUEST['last_name']) ? sanitize_text_field(wp_unslash($_REQUEST['last_name'])) : ($current_user_id ? get_user_meta($current_user_id, 'last_name', true) : '');
?>
    <div class="pmpro_checkout-fields">
        <div class="pmpro_form_field pmpro_form_field-text pmpro_checkout-field-first_name">
            <label for="first_name" class="pmpro_form_label"><?php esc_html_e('First Name', 'pmpro'); ?></label>
            <input id="first_name" name="first_name" type="text" class="pmpro_form_input pmpro_form_input-text pmpro_required" size="30" value="<?php echo esc_attr($first_name); ?>" required />
        </div>

    </div>
    <div class="pmpro_checkout-fields">
        <div class="pmpro_form_field pmpro_form_field-text pmpro_checkout-field-last_name">
            <label for="last_name" class="pmpro_form_label"><?php esc_html_e('Last Name', 'pmpro'); ?></label>
            <input id="last_name" name="last_name" type="text" class="pmpro_form_input pmpro_form_input-text pmpro_required" size="30" value="<?php echo esc_attr($last_name); ?>" required />
        </div>
    </div>

<?php
}
add_action('pmpro_checkout_after_password', 'dd_pmpro_add_name_fields_to_checkout');

/**
 * Validates the custom checkout fields on form submission.
 * Verifies that the First Name and Last Name exist either in the incoming 
 * request payload or are already saved in the database for existing users.
 *
 * @param bool $pmpro_continue_registration Current boolean state of the PMPro registration validation.
 * @return bool Returns true if custom validation passes, or false if an error is registered.
 */
function dd_pmpro_require_name_fields($pmpro_continue_registration)
{
    // Execute custom validation strictly if upstream PMPro core checks pass.
    if ($pmpro_continue_registration) {
        $user_id = get_current_user_id();

        // Check request payload first; if empty and user is logged in, attempt retrieval from user meta.
        $first_name = !empty($_REQUEST['first_name']) ? $_REQUEST['first_name'] : ($user_id ? get_user_meta($user_id, 'first_name', true) : '');
        $last_name  = !empty($_REQUEST['last_name']) ? $_REQUEST['last_name'] : ($user_id ? get_user_meta($user_id, 'last_name', true) : '');

        if (empty($first_name)) {
            pmpro_setMessage(__('Please enter your First Name.', 'pmpro'), 'pmpro_error');
            return false;
        }
        if (empty($last_name)) {
            pmpro_setMessage(__('Please enter your Last Name.', 'pmpro'), 'pmpro_error');
            return false;
        }
    }
    return $pmpro_continue_registration;
}
add_filter('pmpro_registration_checks', 'dd_pmpro_require_name_fields');

/**
 * Writes the captured custom field data to the wp_usermeta table.
 * Executes strictly after PMPro completes the checkout transaction to prevent 
 * overwriting existing meta with blank values from omitted DOM elements.
 *
 * @param int    $user_id The integer ID of the user who successfully completed checkout.
 * @param object $morder  The PMPro membership order object.
 * @return void
 */
function dd_pmpro_save_name_fields_to_usermeta($user_id, $morder)
{
    // Write First Name strictly if explicitly passed in the validated POST request.
    if (!empty($_REQUEST['first_name'])) {
        update_user_meta($user_id, 'first_name', sanitize_text_field(wp_unslash($_REQUEST['first_name'])));
    }

    // Write Last Name strictly if explicitly passed in the validated POST request.
    if (!empty($_REQUEST['last_name'])) {
        update_user_meta($user_id, 'last_name', sanitize_text_field(wp_unslash($_REQUEST['last_name'])));
    }
}
add_action('pmpro_after_checkout', 'dd_pmpro_save_name_fields_to_usermeta', 10, 2);



/** Codes to fix pricing and subscription when changing payment plans and membership*/

/**
 * Remove subscription delay for logged-in current or past members. 
 * EXCEPTION: Leaves the delay active for Level 15.
 */
function my_pmpro_one_time_sub_delay($checkout_level)
{

    // Logged-out users should always get the trial/delay.
    if (! is_user_logged_in()) {
        return $checkout_level;
    }

    // --- LEVEL 15 EXCEPTION ---
    // If the user currently HAS Level 15, OR they are PURCHASING Level 15,
    // bail out immediately so the Subscription Delay remains fully active.
    if (pmpro_hasMembershipLevel(15) || $checkout_level->id == 15) {
        return $checkout_level;
    }

    $order     = new MemberOrder();
    $lastorder = $order->getLastMemberOrder(null, array('success', 'cancelled'));
    $has_delay = get_option('pmpro_subscription_delay_' . $checkout_level->id, '');

    // If user currently has a membership level or previously had a membership level, remove subscription delay.
    if ((pmpro_hasMembershipLevel() || ! empty($lastorder)) && ! empty($has_delay)) {

        // Remove subscription delay filters and actions (standard).
        remove_filter('pmpro_profile_start_date', 'pmprosd_pmpro_profile_start_date', 10, 2);
        remove_action('pmpro_after_checkout', 'pmprosd_pmpro_after_checkout');
        remove_filter('pmpro_next_payment', 'pmprosd_pmpro_next_payment', 10, 3);
        remove_filter('pmpro_level_cost_text', 'pmprosd_level_cost_text', 10, 2);
        remove_action('pmpro_save_discount_code_level', 'pmprosd_pmpro_save_discount_code_level', 10, 2);

        // Remove the updated filter added in PMPro Subscription Delays 3.4+.
        remove_filter('pmpro_checkout_level', 'pmprosd_pmpro_checkout_level', 10, 2);

        // Set the initial amount to match the billing amount.
        if ($checkout_level->billing_amount > 0) {
            $checkout_level->initial_payment = $checkout_level->billing_amount;
        }
    }
    return $checkout_level;
}
add_filter('pmpro_checkout_level', 'my_pmpro_one_time_sub_delay');

/**
 * Helper function to force correct start date for different billing periods
 */
function dd_force_new_billing_cycle_start_date($startdate, $order)
{
    global $dd_new_cycle_number, $dd_new_cycle_period;

    if (! empty($dd_new_cycle_number) && ! empty($dd_new_cycle_period)) {
        // Calculate the exact future date based on the new plan's cycle
        return date('Y-m-d\TH:i:s', current_time('timestamp') + strtotime("+ {$dd_new_cycle_number} {$dd_new_cycle_period}", 0));
    }
    return $startdate;
}

/**
 * Swap in our custom prorating function.
 */
function init_custom_prorating_rules()
{
    remove_filter('pmpro_checkout_level', 'pmprorate_pmpro_checkout_level', 10, 1);
    add_filter('pmpro_checkout_level', 'pmpro_checkout_level_custom_prorating_rules', 10, 1);
}
add_action('init', 'init_custom_prorating_rules');

/**
 * Our custom prorating function
 */
function pmpro_checkout_level_custom_prorating_rules($level)
{
    // Can only prorate if they already have a level
    if (pmpro_hasMembershipLevel()) {
        global $current_user;
        $clevel = $current_user->membership_level;
        $morder = new MemberOrder();
        $morder->getLastMemberOrder($current_user->ID, array('success', '', 'cancelled'));

        // No prorating needed if they don't have an order
        if (empty($morder->timestamp)) {
            return $level;
        }

        // Safely determine the base cost for the new level
        $base_new_level_cost = ($level->initial_payment > 0) ? $level->initial_payment : $level->billing_amount;

        // Do not rely on Level IDs. Check the actual cycle text (e.g. "Month" vs "Year")
        $is_same_period = ($clevel->cycle_number == $level->cycle_number && $clevel->cycle_period == $level->cycle_period);

        // DOWNGRADE LOGIC
        if (pmprorate_isDowngrade($clevel->id, $level->id)) {

            $level->initial_payment = 0;
            
            // CRITICAL FIX: Safely capture the expiration date and intent to the DB before checkout destroys it
            $banked_expiration = pmpro_next_payment($current_user->ID);
            update_user_meta($current_user->ID, 'dd_checkout_intent_old_level', $clevel->id);
            update_user_meta($current_user->ID, 'dd_checkout_intent_new_level', $level->id);
            update_user_meta($current_user->ID, 'dd_checkout_intent_expiration', $banked_expiration);

            // Keep the global for legacy PMPro addons just in case
            global $pmpro_checkout_old_level;
            $pmpro_checkout_old_level = $clevel;

            add_filter('pmpro_profile_start_date', 'pmprorate_set_startdate_to_next_payment_date', 10, 2);

            // UPGRADE LOGIC (SAME BILLING PERIOD)
        } elseif ($is_same_period) {

            $payment_date = pmprorate_trim_timestamp($morder->timestamp);
            $next_payment_date = pmprorate_trim_timestamp(pmpro_next_payment($current_user->ID));
            $today = pmprorate_trim_timestamp(current_time('timestamp'));
            $days_in_period = ceil(($next_payment_date - $payment_date) / 3600 / 24);

            if ($days_in_period <= 0) return $level;

            $days_passed = ceil(($today - $payment_date) / 3600 / 24);
            $per_passed = $days_passed / $days_in_period;
            $per_left   = 1 - $per_passed;

            $new_level_cost = $level->billing_amount * $per_left;
            $old_level_cost = $clevel->billing_amount * $per_passed;

            // HOPSCOTCH FIX: Prevent $0 subtotals from breaking Same-Period math
            $subtotal_to_use = ($morder->subtotal > 0) ? $morder->subtotal : $clevel->billing_amount;

            $level->initial_payment = min($base_new_level_cost, round($new_level_cost + $old_level_cost - $subtotal_to_use, 2));

            if ($level->initial_payment < 0) {
                $level->initial_payment = 0;
            }

            add_filter('pmpro_profile_start_date', 'pmprorate_set_startdate_to_next_payment_date', 10, 2);

            // UPGRADE / DOWNGRADE LOGIC (DIFFERENT BILLING PERIODS - e.g., Monthly <-> Annual)
        } else {

            $payment_date = pmprorate_trim_timestamp($morder->timestamp);
            $next_payment_date = pmprorate_trim_timestamp(pmpro_next_payment($current_user->ID));
            $today = pmprorate_trim_timestamp(current_time('timestamp'));

            $days_left = ceil(($next_payment_date - $today) / 3600 / 24);

            if ($days_left <= 0) return $level;

            // THE HOPSCOTCH FIX: Accurately calculate credit even if the last order was $0
            if ($morder->subtotal > 0) {
                $days_in_period = ceil(($next_payment_date - $payment_date) / 3600 / 24);
                $per_passed = ($days_in_period - $days_left) / $days_in_period;
                $per_left   = 1 - $per_passed;
                $credit = $morder->subtotal * $per_left;
            } else {
                // Last checkout was $0. Calculate the true value of their banked days.
                $cycle_days = 30; // Default to Monthly
                if ($clevel->cycle_period == 'Year') $cycle_days = 365 * $clevel->cycle_number;
                elseif ($clevel->cycle_period == 'Week') $cycle_days = 7 * $clevel->cycle_number;
                elseif ($clevel->cycle_period == 'Day') $cycle_days = $clevel->cycle_number;

                $daily_rate = $clevel->billing_amount / $cycle_days;

                // Fallback to new plan's daily rate if old plan was completely free
                if ($daily_rate <= 0) {
                    $new_cycle_days = 30;
                    if ($level->cycle_period == 'Year') $new_cycle_days = 365 * $level->cycle_number;
                    elseif ($level->cycle_period == 'Week') $new_cycle_days = 7 * $level->cycle_number;
                    elseif ($level->cycle_period == 'Day') $new_cycle_days = $level->cycle_number;

                    $daily_rate = $base_new_level_cost / $new_cycle_days;
                }

                $credit = $days_left * $daily_rate;
            }

            $level->initial_payment = round($base_new_level_cost - $credit, 2);

            // Unhook any lingering Same-Period filters from PMPro core just to be safe
            remove_filter('pmpro_profile_start_date', 'pmprorate_set_startdate_to_next_payment_date', 10);

            // Check if they have surplus credit (e.g. Annual -> Monthly OR Hopscotching)
            if ($level->initial_payment <= 0) {

                // Zero out the cost today
                $level->initial_payment = 0;

                // Force the start date to map exactly to their EXISTING expiration date so they keep their banked time!
                add_filter('pmpro_profile_start_date', 'pmprorate_set_startdate_to_next_payment_date', 99, 2);
            } else {

                // They owe money today. Force the start date to map exactly to the NEW billing cycle!
                global $dd_new_cycle_number, $dd_new_cycle_period;
                $dd_new_cycle_number = $level->cycle_number; // e.g., 1
                $dd_new_cycle_period = $level->cycle_period; // e.g., 'Year'

                add_filter('pmpro_profile_start_date', 'dd_force_new_billing_cycle_start_date', 99, 2);
            }
        }
    }
    return $level;
}


/**
 * -------------------------------------------------------------
 * --- THE DOWNGRADE DELAY ENGINE (STEALTH SQL VERSION) ---
 * Prevents immediate feature loss by stealthily manipulating 
 * the raw database to bypass PMPro's aggressive cancellation hooks.
 * -------------------------------------------------------------
 */

/**
 * 1. Intercept the Downgrade Checkout & Webhook Defense
 */
function dd_stealth_preserve_old_level_on_downgrade($level_id, $user_id, $cancel_level)
{
    // --- PART 1: INITIAL CHECKOUT INTERCEPT (STEALTH SWAP) ---
    $intent_old_level = get_user_meta($user_id, 'dd_checkout_intent_old_level', true);
    $intent_new_level = get_user_meta($user_id, 'dd_checkout_intent_new_level', true);
    $expiration_timestamp = get_user_meta($user_id, 'dd_checkout_intent_expiration', true);

    if (!empty($intent_old_level) && $level_id == $intent_new_level) {
        if (!empty($expiration_timestamp)) {
            global $wpdb;

            // 1. Lock the parameters into the DB for the Daily Worker and Webhook Defense
            update_user_meta($user_id, 'dd_future_downgrade_level', $intent_new_level);
            update_user_meta($user_id, 'dd_future_downgrade_date', $expiration_timestamp);
            update_user_meta($user_id, 'dd_preserved_old_level', $intent_old_level);

            // 2. Clean up the initial checkout intent so it doesn't loop
            delete_user_meta($user_id, 'dd_checkout_intent_old_level');
            delete_user_meta($user_id, 'dd_checkout_intent_new_level');
            delete_user_meta($user_id, 'dd_checkout_intent_expiration');

            // 3. THE STEALTH SWAP: Directly update the raw database row.
            // This bypasses pmpro_changeMembershipLevel entirely, preventing recursive loops and Stripe cancellations.
            $formatted_date = date('Y-m-d H:i:s', $expiration_timestamp);
            $wpdb->query($wpdb->prepare(
                "UPDATE {$wpdb->pmpro_memberships_users}
                 SET membership_id = %d, enddate = %s
                 WHERE user_id = %d AND status = 'active' AND membership_id = %d",
                $intent_old_level, $formatted_date, $user_id, $intent_new_level
            ));

            // 4. Clear PMPro's cache so the frontend dashboard instantly reflects the restored higher level
            if (function_exists('pmpro_clean_membership_cache')) {
                pmpro_clean_membership_cache($user_id);
            }
            return; // Exit here so we don't process part 2 on the same run
        }
    }

    // --- PART 2: STRIPE WEBHOOK DEFENSE ---
    // If a webhook fires seconds later trying to aggressively force the downgrade, block it!
    $future_downgrade_level = get_user_meta($user_id, 'dd_future_downgrade_level', true);
    $future_downgrade_date  = get_user_meta($user_id, 'dd_future_downgrade_date', true);
    $preserved_old_level    = get_user_meta($user_id, 'dd_preserved_old_level', true);

    if (!empty($future_downgrade_level) && $level_id == $future_downgrade_level && current_time('timestamp') < $future_downgrade_date) {
        if (!empty($preserved_old_level)) {
            global $wpdb;

            // A webhook tried to downgrade them. Run the Stealth Swap again to block it.
            $formatted_date = date('Y-m-d H:i:s', $future_downgrade_date);
            $wpdb->query($wpdb->prepare(
                "UPDATE {$wpdb->pmpro_memberships_users}
                 SET membership_id = %d, enddate = %s
                 WHERE user_id = %d AND status = 'active' AND membership_id = %d",
                $preserved_old_level, $formatted_date, $user_id, $level_id
            ));

            // Clear PMPro cache
            if (function_exists('pmpro_clean_membership_cache')) {
                pmpro_clean_membership_cache($user_id);
            }
        }
    }
}
// Run at Priority 99 so we intercept the database AFTER PMPro has finished all of its native operations!
add_action('pmpro_after_change_membership_level', 'dd_stealth_preserve_old_level_on_downgrade', 99, 3);


/**
 * 2. The Daily Background Worker (CRON)
 */
function dd_process_pending_downgrades() {
    global $wpdb;
    $today_timestamp = current_time( 'timestamp' );

    // Find all users who have a pending downgrade scheduled
    $pending_downgrades = $wpdb->get_results( "SELECT user_id, meta_value as downgrade_date FROM {$wpdb->usermeta} WHERE meta_key = 'dd_future_downgrade_date'" );

    foreach ( $pending_downgrades as $pending ) {
        $user_id = $pending->user_id;
        $downgrade_date = (int) $pending->downgrade_date;

        // If their banked time is officially up today (or past)
        if ( $today_timestamp >= $downgrade_date ) {
            $future_level_id = get_user_meta( $user_id, 'dd_future_downgrade_level', true );

            if ( ! empty( $future_level_id ) ) {
                // Because this runs on a background Cron (not during checkout), it is perfectly 
                // safe to use PMPro's official function to safely transition their gateway profile.
                pmpro_changeMembershipLevel( $future_level_id, $user_id );

                // Clean up the database so this user doesn't get processed again
                delete_user_meta( $user_id, 'dd_future_downgrade_level' );
                delete_user_meta( $user_id, 'dd_future_downgrade_date' );
                delete_user_meta( $user_id, 'dd_preserved_old_level' );
            }
        }
    }
}
add_action( 'dd_daily_downgrade_worker', 'dd_process_pending_downgrades' );

/**
 * 3. Theme-Optimized Cron Scheduler
 * Wraps the scheduling check in 'init' so it doesn't run raw on every page load
 */
function dd_register_downgrade_cron() {
    if ( ! wp_next_scheduled( 'dd_daily_downgrade_worker' ) ) {
        wp_schedule_event( time(), 'daily', 'dd_daily_downgrade_worker' );
    }
}
add_action( 'init', 'dd_register_downgrade_cron' );

/** End of Codes to fix pricing and subscription when changing payment plans and membership*/