<?php
if (! defined('ABSPATH')) {
    exit; // Exit if accessed directly to prevent direct file execution.
}

/**
 * Description: Automatically cancels all other active membership levels when a user obtains a new level, regardless of group association.
 */

if (! function_exists('dd_pmpro_enforce_single_membership_global')) {

    /**
     * Cancels all old membership levels when a user is assigned a new one.
     *
     * This hooks into 'pmpro_after_change_membership_level' which runs after
     * a level has been successfully changed/added.
     *
     * @param int $level_id     The ID of the new level being assigned (0 if cancelling).
     * @param int $user_id      The ID of the user.
     * @param int $cancel_level The ID of the level being cancelled (if applicable).
     */
    function dd_pmpro_enforce_single_membership_global($level_id, $user_id, $cancel_level)
    {

        // 1. Safety Check: If $level_id is 0, it means a cancellation is happening.
        // We must exit to prevent an infinite loop of cancellations triggering this hook.
        if (0 === (int) $level_id) {
            return;
        }

        // 2. Retrieve all active membership levels for the user.
        // pmpro_getMembershipLevelsForUser returns an array of level objects, irrespective of groups.
        $user_levels = pmpro_getMembershipLevelsForUser($user_id);

        // 3. Iterate through active levels and cancel any that are not the new level.
        if (! empty($user_levels)) {
            foreach ($user_levels as $level) {

                // Compare IDs to ensure we don't cancel the level specifically just added.
                if ((int) $level->id !== (int) $level_id) {

                    // Cancel the old level.
                    // 'cancelled' uses the 'old_level_status' enum to mark it as cancelled in history.
                    pmpro_cancelMembershipLevel($level->id, $user_id, 'cancelled');

                    // Optional: Log this action for debugging if needed.
                    // error_log( "PMPro Global Enforce: Cancelled Level ID {$level->id} for User ID {$user_id} in favor of Level ID {$level_id}" );
                }
            }
        }
    }

    // Priority 10 is standard; this ensures it runs during the checkout/assignment flow.
    add_action('pmpro_after_change_membership_level', 'dd_pmpro_enforce_single_membership_global', 10, 3);
}


/**
 * Description: Uses MutationObserver to forcefully rename the checkout button on the membership checkout page, overriding payment gateways.
 */

function dd_pmpro_force_checkout_text_observer()
{
    // 1. Target the specific checkout page URL provided
    // We check if we are on the 'membership-checkout' page.
    if (! is_page(1551)) {
        return;
    }
?>
    <script type="text/javascript">
        jQuery(document).ready(function($) {

            // CONFIGURATION: Set your desired button text here
            const newText = "Submit";
            const targetButtonId = "pmpro_btn-submit";

            const $btn = $('#' + targetButtonId);

            if ($btn.length === 0) return;

            // Function to apply the text change
            const forceText = () => {
                if ($btn.is('input')) {
                    // For <input type="submit">
                    if ($btn.val() !== newText) {
                        $btn.val(newText);
                    }
                } else {
                    // For <button> elements
                    if ($btn.text() !== newText) {
                        $btn.text(newText);
                    }
                }
            };

            // 1. Apply immediately
            forceText();

            // 2. Set up a MutationObserver to watch for changes
            // This detects if Stripe/PayPal/Theme tries to overwrite our text
            const observer = new MutationObserver(function(mutations) {
                mutations.forEach(function(mutation) {
                    forceText();
                });
            });

            // Start observing the button for attribute changes (like 'value' or 'disabled') or child list changes (text inside <button>)
            observer.observe($btn[0], {
                attributes: true,
                childList: true,
                subtree: true
            });
        });
    </script>
<?php
}
add_action('wp_footer', 'dd_pmpro_force_checkout_text_observer', 99);



/**
 * Intercepts and modifies localization strings for Paid Memberships Pro.
 * * This function hooks into the WordPress 'gettext' translation system. It checks 
 * if the text domain is PMPro and if the original string matches known lost 
 * password variants, returning a custom string if a match is found.
 *
 * @param string $translated_text The translated text generated by WordPress.
 * @param string $text            The original unmodified string.
 * @param string $domain          The text domain associated with the string.
 * @return string                 The newly defined text or the original translated text.
 */
function dd_pmpro_custom_lost_password_text($translated_text, $text, $domain)
{
    // Strictly target the PMPro text domain to prevent global overrides.
    if ('paid-memberships-pro' === $domain) {

        // Match common PMPro lost password strings. 
        // Note: Exact string matching is required for gettext to work.
        if ('Forgot Password?' === $text || 'Lost Password?' === $text || 'Lost your password?' === $text) {

            // Define the new custom text here.
            $translated_text = esc_html__('Reset password', 'paid-memberships-pro');
        }
    }

    return $translated_text;
}
add_filter('gettext', 'dd_pmpro_custom_lost_password_text', 20, 3);

/**
 * Appends the current user's membership level slug to the body class array.
 * * This function hooks into 'body_class' to inject custom CSS classes based on 
 * the current user's authentication status and membership tier. It checks for 
 * Paid Memberships Pro, WooCommerce Memberships, and falls back to standard 
 * WP roles to ensure a CSS-friendly slug is always generated.
 *
 * @param array $classes An array of existing body classes generated by WordPress.
 * @return array The filtered array of body classes with membership slugs appended.
 */
function dd_append_membership_level_body_class($classes)
{

    // Handle unauthenticated users immediately to reduce processing overhead
    if (! is_user_logged_in()) {
        $classes[] = 'membership-guest';
        return $classes;
    }

    $user_id = get_current_user_id();
    $membership_slugs = array();

    // 1. Paid Memberships Pro (PMPro) Integration
    if (function_exists('pmpro_getMembershipLevelForUser')) {
        $level = pmpro_getMembershipLevelForUser($user_id);
        if (! empty($level) && isset($level->name)) {
            // Converts the string (e.g., "Gold Tier") to a slug (e.g., "pmpro-level-gold-tier")
            $membership_slugs[] = 'pmpro-level-' . sanitize_title($level->name);
            $membership_slugs[] = 'pmpro-level-' . sanitize_title($level->id);
        }
    }


    // 2. Fallback: Standard WordPress User Role
    // If no membership plugin data is found, utilize the assigned WP roles
    if (empty($membership_slugs)) {
        $user = get_userdata($user_id);
        if (! empty($user->roles) && is_array($user->roles)) {
            foreach ($user->roles as $role) {
                $membership_slugs[] = 'role-' . sanitize_title($role);
            }
        }
    }

    // Merge new classes with existing ones, ensuring no duplicates are added
    if (! empty($membership_slugs)) {
        $classes = array_merge($classes, array_unique($membership_slugs));
    }

    return $classes;
}
add_filter('body_class', 'dd_append_membership_level_body_class');



/**
 * Overrides the default logout redirect destination with the PMPro login page URL.
 * Includes a validation check to ensure PMPro is active before attempting to retrieve its routing.
 *
 * @param string  $redirect_to           The default redirect destination URL.
 * @param string  $requested_redirect_to The requested redirect destination URL passed as a parameter.
 * @param WP_User $user                  The WP_User object for the user that is logging out.
 * @return string                        The customized PMPro login URL or the fallback default URL.
 */
function dd_custom_pmpro_logout_redirect($redirect_to, $requested_redirect_to, $user)
{

    // Validate PMPro core functionality exists to prevent fatal errors if the plugin is deactivated
    if (function_exists('pmpro_url')) {

        // Retrieve the designated PMPro login page URL via the core API
        $pmpro_login_url = pmpro_url('login');

        // Ensure a valid URL was returned before applying the redirect override
        if (! empty($pmpro_login_url)) {
            return $pmpro_login_url;
        }
    }

    // Fall back to default WordPress routing if PMPro is unavailable or the URL is empty
    return $redirect_to;
}

// Hook into the logout_redirect filter with a standard priority of 10, accepting 3 arguments
add_filter('logout_redirect', 'dd_custom_pmpro_logout_redirect', 10, 3);

/**
 * Adjusts the profile_start_date and initial_payment for the new membership level during checkout.
 * This ensures the new billing cycle appends to the existing subscription's next payment date appropriately.
 *
 * @param object $level The membership level object being processed at checkout.
 * @return object The modified membership level object.
 */
function dd_pmpro_append_billing_cycle_on_switch($level)
{
    // Ensure the user is authenticated and the level has recurring billing configured.
    if (! is_user_logged_in() || empty($level) || empty($level->billing_amount)) {
        return $level;
    }

    $user_id = get_current_user_id();
    $old_level = pmpro_getMembershipLevelForUser($user_id);

    // Do not abort if they are just switching payment plans within the same tier!
    // Abort ONLY if the Level ID AND the Cycle Period are identical.
    if (empty($old_level) || ($old_level->id == $level->id && $old_level->cycle_period == $level->cycle_period)) {
        return $level;
    }

    // Retrieve the UNIX timestamp for the next scheduled payment of the current active subscription.
    $next_payment_timestamp = pmpro_next_payment($user_id);

    // If no future payment date exists (e.g., cancelled or expired), rely on default PMPro behavior.
    if (! $next_payment_timestamp || $next_payment_timestamp <= current_time('timestamp')) {
        return $level;
    }

    // Extract cycle parameters for comparison and calculation.
    $new_cycle_number = ! empty($level->cycle_number) ? (int) $level->cycle_number : 1;
    $new_cycle_period = ! empty($level->cycle_period) ? $level->cycle_period : 'Month';
    $old_cycle_period = ! empty($old_level->cycle_period) ? $old_level->cycle_period : 'Month';

    // -------------------------------------------------------------------------
    // SCENARIO LOGIC
    // -------------------------------------------------------------------------
    
    if ($old_cycle_period === 'Year' && $new_cycle_period === 'Month') {
        // SCENARIO 1: Annual to Monthly (Downgrade)
        $level->initial_payment = 0;
        $level->profile_start_date = date("Y-m-d\TH:i:s", $next_payment_timestamp);

    } elseif ($old_cycle_period === 'Month' && $new_cycle_period === 'Year') {
        // SCENARIO 2: Monthly to Annual (Upgrade)
        // THE FIX: Explicitly bypass the $0 backend setting so they are charged today.
        $level->initial_payment = $level->billing_amount;
        
        $strtotime_modifier = '+' . $new_cycle_number . ' ' . $new_cycle_period;
        $new_start_timestamp = strtotime($strtotime_modifier, $next_payment_timestamp);
        $level->profile_start_date = date("Y-m-d\TH:i:s", $new_start_timestamp);

    } else {
        // SCENARIO 3: Same Cycle (Month-to-Month or Year-to-Year switch to a different Level ID)
        if ((float)$level->billing_amount > (float)$old_level->billing_amount) {
            // Upgrade: Force the payment today
            $level->initial_payment = $level->billing_amount;
        } else {
            // Downgrade: Owe nothing today
            $level->initial_payment = 0;
        }
        $level->profile_start_date = date("Y-m-d\TH:i:s", $next_payment_timestamp);
    }

    // Ensure the PMPro Subscription Delays add-on doesn't overwrite our calculated date
    remove_filter('pmpro_profile_start_date', 'pmprosd_pmpro_profile_start_date', 10, 2);

    return $level;
}
// THE FIX: Changed priority from 10 to 5. This guarantees our script sets the price 
// BEFORE the PMPro Proration Add-on runs, allowing it to correctly calculate their credit!
add_filter('pmpro_checkout_level', 'dd_pmpro_append_billing_cycle_on_switch', 5, 1);

/**
 * Intercepts frontend page loads to handle two specific free-tier redirections:
 * 1. Redirects users completing checkout for the Free Level (15) directly to the pricing page.
 * 2. Forcefully redirects Free members to the pricing page if they access the dashboard template,
 *    while explicitly exempting core PMPro functional pages to prevent lockouts.
 *
 * @return void
 */
function dd_force_free_members_to_upgrade()
{
    // 1. Abort if Paid Memberships Pro is not active
    if (! function_exists('pmpro_hasMembershipLevel')) {
        return;
    }

    // 2. Abort for backend, AJAX, or logged-out users
    if (! is_user_logged_in() || is_admin() || wp_doing_ajax() || wp_is_json_request()) {
        return;
    }

    global $post, $pmpro_pages;

    // 3. NEW LOGIC: Intercept Free Level (15) Confirmation Page
    // We do this BEFORE the exemption check so it catches the free tier immediately.
    if (! empty($pmpro_pages['confirmation']) && is_page($pmpro_pages['confirmation'])) {
        $level_id = isset($_GET['pmpro_level']) ? intval($_GET['pmpro_level']) : 0;

        if ($level_id === 15) {
            $redirect_url = pmpro_url('levels');
            if ($redirect_url) {
                wp_safe_redirect($redirect_url);
                exit;
            }
        }
    }

    // 4. DEFENSE IN DEPTH: Explicitly exempt core PMPro functional pages
    if (! empty($pmpro_pages)) {
        // Includes 'account' and 'profile' to the exempt keys
        $exempt_keys = array('levels', 'checkout', 'billing', 'cancel', 'confirmation', 'account', 'profile');
        $exempt_page_ids = array();

        foreach ($exempt_keys as $key) {
            if (! empty($pmpro_pages[$key])) {
                $exempt_page_ids[] = $pmpro_pages[$key];
            }
        }

        // Exemption A: Is this an exact match for a core PMPro page?
        if (is_page($exempt_page_ids)) {
            return;
        }

        // Exemption B: Is this a child page of the Membership Account page? (e.g., /membership-account/your-profile/)
        if (! empty($pmpro_pages['account']) && isset($post->post_parent) && $post->post_parent == $pmpro_pages['account']) {
            return;
        }
    }

    // 5. Abort if the current page is NOT using the Dashboard template
    if (! is_page_template('templates/page-dashboard.php')) {
        return;
    }

    // 6. Define the exact ID of your Free Membership Level
    $free_level_ids = array(15);

    // 7. Evaluate if the current user possesses the free level
    if (pmpro_hasMembershipLevel($free_level_ids)) {

        // Retrieve the dynamic URL for the PMPro Levels/Pricing page
        $redirect_url = pmpro_url('levels');

        // Execute the redirect
        if ($redirect_url) {
            wp_safe_redirect($redirect_url);
            exit;
        }
    }
}
add_action('template_redirect', 'dd_force_free_members_to_upgrade');


/**
 * Custom UI for PMPro Checkout - Dynamic Pricing Timeline
 * Replaces the static level cost with the dynamically calculated initial payment and future billing dates.
 */
function dd_influencer_style_pmpro_checkout($cost_text, $level) {
    global $pmpro_level;

    // Bail out and return default if we aren't on an active checkout with a level
    if (empty($pmpro_level) || empty($pmpro_level->id)) {
        return $cost_text;
    }

    // 1. Grab the LIVE math for the checkout today, not just the raw database price
    $paying_now = isset($pmpro_level->initial_payment) ? (float) $pmpro_level->initial_payment : 0;
    $recurring_amount = isset($pmpro_level->billing_amount) ? (float) $pmpro_level->billing_amount : 0;

    // 2. Intelligently determine the "Why" string for the user
    $payment_reason = '';
    if ($paying_now == 0) {
        // They owe nothing today (Downgrade, Banked Time, or Subscription Delay)
        $payment_reason = ' <span style="font-size: 0.9em; color: #666;">(Adjusted for banked time or active delay)</span>';
    } elseif ($paying_now > 0 && $paying_now < $recurring_amount) {
        // They are paying a partial amount (Prorated Upgrade)
        $payment_reason = ' <span style="font-size: 0.9em; color: #666;">(Prorated amount for your upgrade)</span>';
    }

    // 3. Determine the exact date the FULL recurring amount will kick in
    $next_date = '';
    if (!empty($pmpro_level->profile_start_date)) {
        // Use the custom date our previous script locked in
        $next_date = date_i18n(get_option('date_format'), strtotime($pmpro_level->profile_start_date));
    } else {
        // Fallback PMPro calculation if a custom date wasn't set
        $cycle_number = !empty($pmpro_level->cycle_number) ? $pmpro_level->cycle_number : 1;
        $cycle_period = !empty($pmpro_level->cycle_period) ? $pmpro_level->cycle_period : 'Month';
        $next_date = date_i18n(get_option('date_format'), strtotime('+' . $cycle_number . ' ' . $cycle_period));
    }

    // 4. Build and return the new custom HTML timeline
    ob_start();
    ?>
    <div class="infl-checkout-timeline" style="margin-top: 15px;">
        <div class="infl-timeline-item" style="margin-bottom: 8px;">
            <strong>Paying Now:</strong> <?php echo pmpro_formatPrice($paying_now) . $payment_reason; ?>
        </div>

        <?php if ($recurring_amount > 0) : ?>
        <div class="infl-timeline-item">
            <strong>Full Rate Resumes:</strong> <?php echo pmpro_formatPrice($recurring_amount); ?> on <?php echo $next_date; ?>
        </div>
        <?php endif; ?>
    </div>
    <?php
    $custom_html = ob_get_clean();

    // Override the default PMPro text with our custom timeline
    return $custom_html;
}
// Ensure this hooks into PMPro's level cost text filter
add_filter('pmpro_level_cost_text', 'dd_influencer_style_pmpro_checkout', 20, 2);

/**
 * Renders the First Name and Last Name input fields on the PMPro checkout form.
 * Hooks into 'pmpro_checkout_after_password' to insert the fields directly 
 * within the user account credential section. Automatically pre-populates 
 * data for authenticated users to prevent data entry redundancy.
 *
 * @return void
 */
function dd_pmpro_add_name_fields_to_checkout()
{
    $current_user_id = get_current_user_id();

    // Prioritize active POST request data for repopulation, fallback to existing user meta if authenticated.
    $first_name = isset($_REQUEST['first_name']) ? sanitize_text_field(wp_unslash($_REQUEST['first_name'])) : ($current_user_id ? get_user_meta($current_user_id, 'first_name', true) : '');
    $last_name  = isset($_REQUEST['last_name']) ? sanitize_text_field(wp_unslash($_REQUEST['last_name'])) : ($current_user_id ? get_user_meta($current_user_id, 'last_name', true) : '');
?>
    <div class="pmpro_checkout-fields">
        <div class="pmpro_form_field pmpro_form_field-text pmpro_checkout-field-first_name">
            <label for="first_name" class="pmpro_form_label"><?php esc_html_e('First Name', 'pmpro'); ?></label>
            <input id="first_name" name="first_name" type="text" class="pmpro_form_input pmpro_form_input-text pmpro_required" size="30" value="<?php echo esc_attr($first_name); ?>" />
        </div>

    </div>
    <div class="pmpro_checkout-fields">
        <div class="pmpro_form_field pmpro_form_field-text pmpro_checkout-field-last_name">
            <label for="last_name" class="pmpro_form_label"><?php esc_html_e('Last Name', 'pmpro'); ?></label>
            <input id="last_name" name="last_name" type="text" class="pmpro_form_input pmpro_form_input-text pmpro_required" size="30" value="<?php echo esc_attr($last_name); ?>" />
        </div>
    </div>

<?php
}
add_action('pmpro_checkout_after_password', 'dd_pmpro_add_name_fields_to_checkout');

/**
 * Validates the custom checkout fields on form submission.
 * Verifies that the First Name and Last Name exist either in the incoming 
 * request payload or are already saved in the database for existing users.
 *
 * @param bool $pmpro_continue_registration Current boolean state of the PMPro registration validation.
 * @return bool Returns true if custom validation passes, or false if an error is registered.
 */
function dd_pmpro_require_name_fields($pmpro_continue_registration)
{
    // Execute custom validation strictly if upstream PMPro core checks pass.
    if ($pmpro_continue_registration) {
        $user_id = get_current_user_id();

        // Check request payload first; if empty and user is logged in, attempt retrieval from user meta.
        $first_name = !empty($_REQUEST['first_name']) ? $_REQUEST['first_name'] : ($user_id ? get_user_meta($user_id, 'first_name', true) : '');
        $last_name  = !empty($_REQUEST['last_name']) ? $_REQUEST['last_name'] : ($user_id ? get_user_meta($user_id, 'last_name', true) : '');

        if (empty($first_name)) {
            pmpro_setMessage(__('Please enter your First Name.', 'pmpro'), 'pmpro_error');
            return false;
        }
        if (empty($last_name)) {
            pmpro_setMessage(__('Please enter your Last Name.', 'pmpro'), 'pmpro_error');
            return false;
        }
    }
    return $pmpro_continue_registration;
}
add_filter('pmpro_registration_checks', 'dd_pmpro_require_name_fields');

/**
 * Writes the captured custom field data to the wp_usermeta table.
 * Executes strictly after PMPro completes the checkout transaction to prevent 
 * overwriting existing meta with blank values from omitted DOM elements.
 *
 * @param int    $user_id The integer ID of the user who successfully completed checkout.
 * @param object $morder  The PMPro membership order object.
 * @return void
 */
function dd_pmpro_save_name_fields_to_usermeta($user_id, $morder)
{
    // Write First Name strictly if explicitly passed in the validated POST request.
    if (!empty($_REQUEST['first_name'])) {
        update_user_meta($user_id, 'first_name', sanitize_text_field(wp_unslash($_REQUEST['first_name'])));
    }

    // Write Last Name strictly if explicitly passed in the validated POST request.
    if (!empty($_REQUEST['last_name'])) {
        update_user_meta($user_id, 'last_name', sanitize_text_field(wp_unslash($_REQUEST['last_name'])));
    }
}
add_action('pmpro_after_checkout', 'dd_pmpro_save_name_fields_to_usermeta', 10, 2);


/** Codes to fix pricing and subscription when changing payment plans and membership*/

/**
 * Remove subscription delay for logged-in current or past members. 
 * EXCEPTION: Leaves the delay active for Level 15.
 */
function my_pmpro_one_time_sub_delay($checkout_level)
{

    // Logged-out users should always get the trial/delay.
    if (! is_user_logged_in()) {
        return $checkout_level;
    }

    // --- LEVEL 15 EXCEPTION ---
    // If the user currently HAS Level 15, OR they are PURCHASING Level 15,
    // bail out immediately so the Subscription Delay remains fully active.
    if (pmpro_hasMembershipLevel(15) || $checkout_level->id == 15) {
        return $checkout_level;
    }

    $order     = new MemberOrder();
    $lastorder = $order->getLastMemberOrder(null, array('success', 'cancelled'));
    $has_delay = get_option('pmpro_subscription_delay_' . $checkout_level->id, '');

    // If user currently has a membership level or previously had a membership level, remove subscription delay.
    if ((pmpro_hasMembershipLevel() || ! empty($lastorder)) && ! empty($has_delay)) {

        // Remove subscription delay filters and actions (standard).
        remove_filter('pmpro_profile_start_date', 'pmprosd_pmpro_profile_start_date', 10, 2);
        remove_action('pmpro_after_checkout', 'pmprosd_pmpro_after_checkout');
        remove_filter('pmpro_next_payment', 'pmprosd_pmpro_next_payment', 10, 3);
        remove_filter('pmpro_level_cost_text', 'pmprosd_level_cost_text', 10, 2);
        remove_action('pmpro_save_discount_code_level', 'pmprosd_pmpro_save_discount_code_level', 10, 2);

        // Remove the updated filter added in PMPro Subscription Delays 3.4+.
        remove_filter('pmpro_checkout_level', 'pmprosd_pmpro_checkout_level', 10, 2);
    }
    return $checkout_level;
}
add_filter('pmpro_checkout_level', 'my_pmpro_one_time_sub_delay');
