<?php
/**
 * Plugin Name: PMPro AJAX Signup Form
 * Plugin URI:  https://digitallydisruptive.co.uk/
 * Description: Converts the PMPro Signup form into an AJAX-driven form via inline JS, preventing page reloads on validation errors while retaining native file upload support.
 * Version:     1.0.1
 * Author:      Digitally Disruptive - Donald Raymundo
 * Author URI:  https://digitallydisruptive.co.uk/
 * License:     GPL-2.0+
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

if ( ! class_exists( 'DD_PMPro_Ajax_Signup' ) ) {

    /**
     * Core plugin class for handling PMPro AJAX Signup integrations.
     *
     * This class encapsulates the hooks and methods required to extend
     * the Paid Memberships Pro signup form with AJAX validation via inline
     * JavaScript and custom profile fields (like avatars), utilizing an
     * object-oriented architecture.
     */
    class DD_PMPro_Ajax_Signup {

        /**
         * Plugin version identifier.
         *
         * @var string
         */
        private $version = '1.0.1';

        /**
         * Initializes the class and registers WordPress hooks.
         *
         * The constructor binds the required actions to their respective
         * WordPress lifecycle hooks to inject inline scripts into the footer
         * and register PMPro user fields upon instantiation.
         *
         * @return void
         */
        public function __construct() {
            add_action( 'wp_footer', array( $this, 'inject_inline_script' ) );
            add_action( 'init', array( $this, 'add_avatar_field' ) );
        }

        /**
         * Injects the necessary JavaScript for AJAX form validation directly into the footer.
         *
         * Hooked to 'wp_footer', this method ensures the AJAX handler 
         * is loaded inline only when Paid Memberships Pro is active on the site,
         * bypassing the need for an additional HTTP request for an external JS file.
         *
         * @return void
         */
        public function inject_inline_script() {
            // Verify PMPro is active before injecting script payloads.
            if ( ! function_exists( 'pmpro_url' ) ) {
                return;
            }
            ?>
            <script type="text/javascript">
            /**
             * PMPro AJAX Signup Form Handler
             * Intercepts the PMPro checkout form submission, sends data via Fetch API,
             * and updates the DOM with validation errors natively generated by PMPro 
             * without reloading the page. Uses FormData to ensure binary files (avatars)
             * are transmitted correctly.
             */
            document.addEventListener('DOMContentLoaded', function() {
                
                /**
                 * Target the main PMPro form wrapper.
                 * PMPro universally assigns the #pmpro_form ID to its checkout forms.
                 */
                const form = document.getElementById('pmpro_form');
                if (!form) return;

                form.addEventListener('submit', async function(e) {
                    e.preventDefault();

                    const submitBtn = form.querySelector('input[type="submit"], button[type="submit"], #pmpro_btn-submit');
                    if (!submitBtn) {
                        form.submit(); // Fallback if structural anomalies exist
                        return;
                    }

                    const originalText = submitBtn.value || submitBtn.textContent || 'Processing...';
                    
                    // Disable the submit button to prevent duplicate asynchronous requests
                    if (submitBtn.tagName.toLowerCase() === 'input') {
                        submitBtn.value = 'Processing...';
                    } else {
                        submitBtn.textContent = 'Processing...';
                    }
                    submitBtn.disabled = true;

                    // Instantiate FormData to capture all textual and file inputs natively
                    const formData = new FormData(form);
                    
                    /**
                     * PMPro Core Architecture Check:
                     * PMPro heavily relies on the 'submit-checkout' POST variable to initiate 
                     * the checkout processing sequence. Because submit buttons are not always 
                     * appended to FormData on intercept, we manually inject it.
                     */
                    if (!formData.has('submit-checkout')) {
                        formData.append('submit-checkout', '1');
                    }

                    try {
                        // Execute POST request to the current URI to trigger standard PMPro validation
                        const response = await fetch(window.location.href, {
                            method: 'POST',
                            body: formData,
                            redirect: 'follow' 
                        });

                        // If PMPro validations pass, it issues a 302 redirect to the confirmation page.
                        if (response.redirected) {
                            window.location.href = response.url;
                            return;
                        }

                        // Extract DOM string from response for parsing
                        const html = await response.text();
                        const parser = new DOMParser();
                        const doc = parser.parseFromString(html, 'text/html');

                        // Identify error message nodes within the virtual DOM
                        const pmproMessage = doc.querySelector('#pmpro_message, .pmpro_error');
                        const existingMessage = document.querySelector('#pmpro_message, .pmpro_error');

                        if (pmproMessage && pmproMessage.classList.contains('pmpro_error')) {
                            // Validation failed: Inject the error message dynamically
                            if (existingMessage) {
                                existingMessage.replaceWith(pmproMessage);
                            } else {
                                form.parentNode.insertBefore(pmproMessage, form);
                            }
                            
                            // Restore button state
                            if (submitBtn.tagName.toLowerCase() === 'input') {
                                submitBtn.value = originalText;
                            } else {
                                submitBtn.textContent = originalText;
                            }
                            submitBtn.disabled = false;

                            // Guide user attention to the error via smooth scroll
                            pmproMessage.scrollIntoView({ behavior: 'smooth', block: 'center' });
                        } else if (doc.querySelector('.pmpro_confirmation_wrap')) {
                            // Fallback: If success redirect was masked, swap the UI wrapper entirely
                            const signupWrap = document.querySelector('.pmpro_signup_wrap');
                            if (signupWrap) {
                                signupWrap.replaceWith(doc.querySelector('.pmpro_confirmation_wrap'));
                            } else {
                                window.location.reload();
                            }
                        } else {
                            // Failsafe: Allow standard synchronous submission for unknown states 
                            // (e.g., third-party gateway redirects via JS)
                            form.removeEventListener('submit', arguments.callee);
                            form.submit();
                        }

                    } catch (error) {
                        console.error('PMPro AJAX Validation Error:', error);
                        // Fallback to synchronous form submission on network failure
                        form.removeEventListener('submit', arguments.callee);
                        form.submit(); 
                    }
                });
            });
            </script>
            <?php
        }

        /**
         * Adds a custom user avatar field to the PMPro signup form.
         *
         * Utilizing the PMPro Field API, this method registers a 'user_avatar' 
         * file input within the 'profile' field group, allowing users to upload 
         * an image during registration.
         *
         * @return void
         */
        public function add_avatar_field() {
            // Check if PMPro is active
            if ( ! function_exists( 'pmpro_add_user_field' ) ) {
                return;
            }

            // Define the avatar field
            $field = new PMPro_Field(
                'user_avatar', // Meta key used by some avatar plugins
                'file',        // Field type
                array(
                    'label'        => 'Profile Picture',
                    'profile'      => true,      // Show on frontend profile
                    'preview'      => true,      // Show image preview
                    'allow_delete' => true,      // Allow deletion
                    'hint'         => 'Recommended size: 200x200 pixels.'
                )
            );

            // Add to the 'profile' group
            pmpro_add_user_field( 'profile', $field );
        }
    }

    // Instantiate the class to boot up the plugin functionality.
    new DD_PMPro_Ajax_Signup();
}